config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles
  put '/article/:id/like', to: 'articles#like', as: 'like'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :section, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :download_articles, only: %i[index show]
  before_action :set_article, only: %i[show]

  # GET /articles or /articles.json
  def index
    @articles = Article.all.order(updated_at: :desc)
    flash.notice = 'No articles found' unless @articles.count
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # PUT /article/1/like
  def like
    @article = Article.find(params[:id])
    @article.increment!(:likes)
    redirect_to article_path(@article)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description, :section)
  end

  def download_articles
    last_modification = Article.maximum(:updated_at)
    downloader = S3DownloadService.new(
      bucket: ENV['AWS_BUCKET_NAME'],
      key: ENV['AWS_OBJECT_NAME'],
      modification_date: last_modification
    )
    ArticleDownloadJob.new(downloader: downloader).perform
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= article.section %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= article.likes %>
  </p>

</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Section</th>
        <th scope="col">Likes</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td>
            <%= article.title %>
          </td>
          <td>
            <%= article.section %>
          </td>
          <td>
            <%= article.likes %>
          </td>
          <td>
            <%= link_to "Show this article", article %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @article %>">
  <h1>
    <%= @article.section.capitalize %> - <%= @article.title %>
  </h1>

  <p>
    <%= @article.description %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= @article.likes %>
  </p>

</div>

<div>
  <%= button_to "Like this article", like_path(@article), method: :put, class: 'btn btn-success' %>
</div>
<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olio Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand text-light" href="/articles">Home</a>
      </div>
    </nav>
    <div class="container text-center"><%= yield %></div>
  </body>
</html>